# Generated by Django 5.1.4 on 2025-01-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crn', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('lecture_times', models.CharField(max_length=100)),
                ('lab_times', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
    ]
