# Generated by Django 5.1.4 on 2025-01-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='item_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
