# Generated by Django 5.1.4 on 2025-01-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_class_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='course_id',
        ),
        migrations.AddField(
            model_name='class',
            name='course_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
