# Generated by Django 5.1.4 on 2025-01-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_class_course_id_class_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='item_id',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('classes', models.ManyToManyField(related_name='students', to='api.class')),
            ],
        ),
    ]
