# Generated by Django 5.1.4 on 2025-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_class_item_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='lab_times',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='lecture_times',
            new_name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
