# Generated by Django 5.1.4 on 2025-01-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_lab_times_class_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
