# Generated by Django 5.1.4 on 2025-01-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='type',
            field=models.CharField(default='Lecture', max_length=100),
            preserve_default=False,
        ),
    ]
