# Generated by Django 5.1.4 on 2025-01-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
